beyond-sw-camp/be12-fin-Catcher-GrapeField-BE

src/main/java/com/example/demo/base/ApiErrorResponses.java
src/main/java/com/example/demo/base/ErrorResponse.java
src/main/java/com/example/demo/events/EventsController.java
src/main/java/com/example/demo/events/EventsRepository.java
src/main/java/com/example/demo/events/EventsService.java
src/main/java/com/example/demo/events/model/entity/SeatPrice.java
src/main/java/com/example/demo/events/model/entity/TicketInfo.java
src/main/java/com/example/demo/events/model/request/EventsImgRegisterReq.java
src/main/java/com/example/demo/events/model/request/EventsRegisterReq.java
src/main/java/com/example/demo/events/model/request/SeatPriceRegisterReq.java
src/main/java/com/example/demo/events/model/request/TicketInfoRegisterReq.java
src/main/java/com/example/demo/events/model/response/EventsDetailResp.java
src/main/java/com/example/demo/events/model/response/EventsImgDetailReq.java
src/main/java/com/example/demo/events/model/response/EventsListResp.java
src/main/java/com/example/demo/events/model/response/SeatPriceDetailReq.java
src/main/java/com/example/demo/events/model/response/TicketInfoDetailResp.java
src/main/java/com/example/demo/events/post/BoardRepository.java
src/main/java/com/example/demo/events/post/CommentController.java
src/main/java/com/example/demo/events/post/PostController.java
src/main/java/com/example/demo/events/post/PostRepository.java
src/main/java/com/example/demo/events/post/PostService.java
src/main/java/com/example/demo/events/post/model/entity/Board.java
src/main/java/com/example/demo/events/post/model/entity/Post.java
src/main/java/com/example/demo/events/post/model/request/CommentRegisterReq.java
src/main/java/com/example/demo/events/post/model/request/PostRegisterReq.java
src/main/java/com/example/demo/events/post/model/response/CommentListResp.java
src/main/java/com/example/demo/events/post/model/response/PostDetailResp.java
src/main/java/com/example/demo/events/post/model/response/PostListResp.java
src/main/java/com/example/demo/user/UserController.java
src/main/java/com/example/demo/user/model/request/UserSignupReq.java

#2 
게시글 작성 및 댓글 관련 Swagger 가
어떤 변경 사항이 있나요?

Feat/swagger 작성

---

Dockerfile

[ADD] docker 빌드를 위한 Dockerfile 추가

---

src/main/java/com/example/grapefield/notification/model/entity/EventsInterest.java
src/main/java/com/example/grapefield/notification/model/entity/EventsNotification.java
src/main/java/com/example/grapefield/notification/model/entity/NotificationType.java
src/main/java/com/example/grapefield/user/model/entity/User.java

[fix] notification 관련 패키지 events 밖으로 이동

---

src/main/java/com/example/grapefield/chat/repository/ChatMessageBaseRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java

#29 채팅 메시지 저장 repository 생성
기능 구현을 위해 repository만 먼저 생성했습니다.
어떤 변경 사항이 있나요?

feat: 채팅 메시지 저장 Repository 생성 #29

---

src/main/java/com/example/grapefield/chat/service/ChatMessageService.java

#34 ChatMessageService 수정
수정 후에는 chat_message_base, chat_Message_current에 모두 동일한 사용자, 동일한 채팅방, 동일한 내용을 보내더라도 중복되어 저장되는 것을 확인(시간은 모두 다름)
같은 사용자가 한개의 채팅방에서 내용을 여러번 보내더라도 서비스에 반영이 되어야 하기 때문에 수정했습니다. 
어떤 변경 사항이 있나요?
확인을 해보니 채팅을 보내는 시간 처리에 대한 여러가지 방식이 있습니다.
1.  ChatMessageBase 엔티티에서 @PrePersist 사용 → 엔티티 내부에서 자동 설정 방식
2.  서비스 단에서 LocalDateTime.now() 직접 설정 → 더 세밀한 제어가 필요할 때 사용한다고 하여 현재는 2번을 사용했는데
확인해보시고 더 좋은 방안이나 아이디어가 있으면 공유해주세요~

fix: ChatMessageService 수정 #34

---

src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java

#24 #25 
- 클라이언트가 메시지를 수신하기 위한 `ChatWebSocketController.java` 작성
- `ChatWebSocketController.java`에 있던 기존의 'kafk로 이벤트(메시지)를 전송하는 코드'를 `ChatKafkaProducer.java` 로 분리
- 파라미터 어노테이션 변경: `@DestinationVariable` 대신에 STOMP&DTO 방식인 `@Payload`로 변경
어떤 변경 사항이 있나요?

[feat] 웹소켓컨트롤러, 카프카 프로듀서

---

.init_merge_branch.txt

#47 브랜치 푸시를 위해 추가했던 txt 파일 삭제
브랜치 푸시를 위해 추가했던 txt 파일 삭제
어떤 변경 사항이 있나요?

[#47] 브랜치 푸시를 위해 추가했던 txt 파일 삭제 커밋

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomController.java
src/main/java/com/example/grapefield/chat/model/response/ChatListResp.java
src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
src/main/java/com/example/grapefield/config/SecurityConfig.java

#52 참여중인 채팅방 목록 불러오기
참여중인 채팅방 목록 불러오기
어떤 변경 사항이 있나요?
수정사항 있으면 공유해주세요~

[#52] 참여중인 채팅방 목록 가져오기

---

src/main/java/com/example/grapefield/common/BoardInitializer.java
src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java
src/main/java/com/example/grapefield/events/EventsController.java
src/main/java/com/example/grapefield/events/EventsService.java
src/main/java/com/example/grapefield/events/post/PostController.java
src/main/java/com/example/grapefield/events/post/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/PostCustomRepositoryImpl.java
src/main/java/com/example/grapefield/events/post/PostRepository.java
src/main/java/com/example/grapefield/events/post/PostService.java
src/main/java/com/example/grapefield/events/post/model/entity/PostType.java
src/main/java/com/example/grapefield/events/post/model/response/PostListResp.java
src/main/java/com/example/grapefield/user/CurrentUser.java
src/main/java/com/example/grapefield/user/CustomUserDetails.java

AuthenticationPrincipal로는 유저 정보를 받아오지 못하는 문제 수정 CurrentUser를 사용 권장
어떤 변경 사항이 있나요?

[fix] 유저 정보 추출 실패 수정 

---

src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/events/post/PostController.java
src/main/java/com/example/grapefield/events/post/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/PostCustomRepositoryImpl.java
src/main/java/com/example/grapefield/events/post/PostService.java
src/main/java/com/example/grapefield/events/post/model/response/PostDetailResp.java
src/main/java/com/example/grapefield/user/CustomUserDetails.java

게시글 상세 내용 반환 및 프론트엔드와 연결
#46
게시글 상세 내용 반환 및 프론트엔드와 연결
어떤 변경 사항이 있나요?

[feat] 게시글 상세 내용 반환

---

src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/config/filter/LoginFilter.java
src/main/java/com/example/grapefield/events/post/CommentController.java
src/main/java/com/example/grapefield/events/post/CommentService.java
src/main/java/com/example/grapefield/events/post/PostController.java
src/main/java/com/example/grapefield/events/post/model/request/CommentRegisterReq.java
src/main/java/com/example/grapefield/events/post/model/response/CommentListResp.java
src/main/java/com/example/grapefield/events/post/repository/PostCommentCustomRepository.java
src/main/java/com/example/grapefield/events/post/repository/PostCommentCustomRepositoryImpl.java
src/main/java/com/example/grapefield/events/post/repository/PostCommentRepository.java
src/main/java/com/example/grapefield/user/CustomUserDetails.java

#61 
댓글 등록 기능 추가, 댓글 목록 가져오기 기능
기존에 record로 선언되어있던 CustomUserDetails를 class로 변환 및 LoginFilter에서 관련 부분 변경
어떤 변경 사항이 있나요?

[feat] 댓글 등록 및 목록 반환

---

src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/UserService.java
src/main/java/com/example/grapefield/user/model/request/UserInfoDetailReq.java
src/main/java/com/example/grapefield/user/repository/UserRepository.java

#64
비밀번호 찾기 및 정보 수정 가능
어떤 변경 사항이 있나요?

#64 마이페이지 개인정보 수정

---

src/main/java/com/example/grapefield/events/review/ReviewController.java
src/main/java/com/example/grapefield/events/review/ReviewService.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepository.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepositoryImpl.java

한줄평 목록을 가져오는 것과 등록하는 기능을 추가하여 프론트와 연동, 별점 필터링 기능 포함
어떤 변경 사항이 있나요?

[feat]한줄평 목록 보기 및 등록 기능 추가

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/java/com/example/grapefield/chat/model/response/ChatListPageResp.java
src/main/java/com/example/grapefield/chat/model/response/ChatListResp.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java
src/main/java/com/example/grapefield/config/SecurityConfig.java

#68 채팅방 목록 리스트 불러오기 구현
채팅방 목록 리스트 불러오기 구현
어떤 변경 사항이 있나요?
채팅방 목록 리스트 구현입니다.. 채팅방이 많아서 속도 개선을 위해 추후에 코드 변경 예정입니당

[#68] 채팅방 목록 리스트 불러오기 구현

---

build.gradle
src/main/java/com/example/grapefield/config/RedisConfig.java
src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java
src/main/java/com/example/grapefield/config/filter/LoginFilter.java
src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/UserService.java
src/main/java/com/example/grapefield/utils/JwtUtil.java
src/main/resources/application.yml

#72 
redis에 로그인 정보를 추가하여 로그인, 로그아웃 관리
어떤 변경 사항이 있나요?

[fix] ATOKEN 외에도 RTOKEN 추가

---

src/main/java/com/example/grapefield/events/EventsController.java
src/main/java/com/example/grapefield/events/EventsService.java
src/main/java/com/example/grapefield/events/model/response/EventsDetailCalendarListResp.java
src/main/java/com/example/grapefield/events/repository/EventsCustomRepository.java
src/main/java/com/example/grapefield/events/repository/EventsCustomRepositoryImpl.java

#75
- dto, 컨트롤러
어떤 변경 사항이 있나요?

#75 상세 캘린더 수정

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
src/main/java/com/example/grapefield/chat/controller/ChatRoomDetailController.java
src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
src/main/java/com/example/grapefield/chat/model/response/ChatHighlightResp.java
src/main/java/com/example/grapefield/chat/model/response/ChatMessageResp.java
src/main/java/com/example/grapefield/chat/model/response/ChatRoomDetailResp.java
src/main/java/com/example/grapefield/chat/model/response/ChatRoomMemberResp.java
src/main/java/com/example/grapefield/chat/repository/ChatHighlishtRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatMessageArchiveRepository.java
src/main/java/com/example/grapefield/chat/service/ChatMessageService.java
src/main/java/com/example/grapefield/chat/service/ChatRoomService.java

#55
채팅방화면 불러오기 컨트롤러 & 새로운 메세지 송수싱 양식 변경
어떤 변경 사항이 있나요?

[feat] 채팅방화면 불러오기 컨트롤러 & 새로운 메세지 송수싱 양식 변경

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java
src/main/java/com/example/grapefield/chat/service/ChatRoomMemberService.java

#81  채팅방 목록 리스트 속도 개선
채팅방 목록 리스트 속도 개선, n+1문제 등을 위한 수정
어떤 변경 사항이 있나요?
혹시 로직 분리를 하는게 좋겠다 싶으면 알려주시면 감사하겠습니다~

[#81] 채팅방 목록 리스트 불러오기_ 성능 개선

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/java/com/example/grapefield/chat/controller/ChatRoomMemberController.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java

Feat/chat/my room 코드 에러 수정

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomMemberController.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/example/grapefield/chat/service/ChatRoomMemberService.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java

#93 채팅 입장 기능 수정, 퇴장 기능 구현
채팅 입장 기능 수정, 퇴장 기능 구현
어떤 변경 사항이 있나요?
채팅 입장, 퇴장 로직 수정, 추가 했습니다~

[#93] 채팅 입장 기능 수정, 퇴장 기능 구현

---

src/main/java/com/example/grapefield/config/SecurityConfig.java

#95
누락된 "/chat/**" URI 접근 허용 추가
어떤 변경 사항이 있나요?

[fix] chat/** URI 누락 오류 수정

---

src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java
src/main/java/com/example/grapefield/config/filter/LoginFilter.java
src/main/java/com/example/grapefield/events/EventsController.java
src/main/java/com/example/grapefield/events/EventsSearchController.java
src/main/java/com/example/grapefield/events/EventsSearchService.java
src/main/java/com/example/grapefield/events/model/entity/Events.java
src/main/java/com/example/grapefield/events/model/response/EventsListResp.java
src/main/java/com/example/grapefield/events/post/PostService.java
src/main/java/com/example/grapefield/events/post/model/entity/Post.java
src/main/java/com/example/grapefield/events/post/model/entity/PostComment.java
src/main/java/com/example/grapefield/events/post/model/response/PostSearchListResp.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepositoryImpl.java
src/main/java/com/example/grapefield/events/repository/EventsCustomRepository.java
src/main/java/com/example/grapefield/events/repository/EventsCustomRepositoryImpl.java
src/main/java/com/example/grapefield/events/review/ReviewController.java
src/main/java/com/example/grapefield/events/review/ReviewService.java
src/main/java/com/example/grapefield/events/review/model/entity/Review.java
src/main/java/com/example/grapefield/events/review/model/response/ReviewListResp.java
src/main/java/com/example/grapefield/events/review/model/response/ReviewSearchList.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepository.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/com/example/grapefield/user/AuthController.java
src/main/java/com/example/grapefield/user/AuthService.java
src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/customercenter/CustomerCenterController.java
src/main/java/com/example/grapefield/utils/CookieUtil.java

#77 
공연/전시, 게시글, 한줄평 검색
어떤 변경 사항이 있나요?

[Feat/search/events/all]

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java

#107 채팅 메시지 저장을 카프카 사용으로 리팩토링
제대로 카프카 설정이 안 된 부분이 있어서 저장 로직을 리팩토링
어떤 변경 사항이 있나요?

[#107] 채팅 메시지 저장 로직을 카프카 사용으로 리팩토링

---

src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
src/main/java/com/example/grapefield/chat/service/ChatRoomService.java

#267
채팅방 좋아요(하트)기능 카프카 컨슈머/프로듀서 구성
멀티팩토리 방식-KafkaConfig.java에서 설정을 따름
추가적으로 약간의 오타를 수정해놓음
어떤 변경 사항이 있나요?

[feat/chatroom/kafka] 채팅방 좋아요(하트) - 카프카 기능

---

src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
src/main/java/com/example/grapefield/chat/service/KafkaTopicService.java

#109
Kafka 토픽 보장 로직을 KafkaTopicService로 분리
어떤 변경 사항이 있나요?

[refactor] KafkaTopicService로 로직분리

---

src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java

#267
토픽 그룹 이름 오타 수정
어떤 변경 사항이 있나요?

[refactor] 오타 수정

---

src/main/java/com/example/grapefield/events/post/PostController.java
src/main/java/com/example/grapefield/events/post/PostService.java
src/main/java/com/example/grapefield/events/post/model/response/CommunityPostListResp.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepositoryImpl.java

#112 
인기, 최신글 조회 및 게시글 이동 가능
어떤 변경 사항이 있나요?

#112 인기, 최신 게시글 조회

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/java/com/example/grapefield/chat/repository/custom/ChatRoomRepositoryCustom.java
src/main/java/com/example/grapefield/chat/repository/custom/ChatRoomRepositoryImpl.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java

#115 채팅방 목록 인기순(하트수) 채팅방 목록 로직
채팅방 목록 인기순(하트수) 채팅방 목록 로직
어떤 변경 사항이 있나요?

[#115] 전체 채팅방 인기순(하트수) 채팅방 목록 로직

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java

#267
오타 수정
어떤 변경 사항이 있나요?
오타 수정이 제대로 커밋되지 않아서 잦은 병합시도한 점 죄송합니다

[fix] 오타 수정

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java

#118
미존재 토픽 발행 실패 오류 수정
어떤 변경 사항이 있나요?

[fix] 오류 수정 토픽 보장 및 생성 로직 순서 변경

---

src/main/java/com/example/grapefield/events/post/model/response/UserPostListResp.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepositoryImpl.java
src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/UserService.java

#125
controller, service, dto 추가
어떤 변경 사항이 있나요?

#125 마이페이지 글 관리

---

src/main/java/com/example/grapefield/events/post/model/response/UserCommentListResp.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepository.java
src/main/java/com/example/grapefield/events/post/repository/PostCustomRepositoryImpl.java
src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/UserService.java

#129
controller, service, dto 생성 및 데이터 보내기
어떤 변경 사항이 있나요?

#129 마이페이지 작성 댓글 관리

---

src/main/java/com/example/grapefield/events/post/model/response/UserReviewListResp.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepository.java
src/main/java/com/example/grapefield/events/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/com/example/grapefield/user/UserController.java
src/main/java/com/example/grapefield/user/UserService.java

#131
한줄평 관련 controller, service, dto 기능 구현
어떤 변경 사항이 있나요?

#131 마이페이지_한줄평 관리

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
src/main/java/com/example/grapefield/chat/config/TopicInitializer.java
src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/resources/application.yml

#134
CreateIfNotExists 방식의 로직 수행하는 KafkaService 제거하고, TopicInitializer 클래스로 실행시 모든 토픽 일괄 생성하도록 함
어떤 변경 사항이 있나요?

[feat] 카프카 토픽 실행시 일괄 생성하도록 변경

---

Dockerfile

[fix] 도커 파일 수정

---

build.gradle
src/main/java/com/example/grapefield/config/ActuatorSecurityConfig.java
src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/resources/application.yml

#141
- 클래스 파일 빈 등록
- security  uri 접속 허용 추가
어떤 변경 사항이 있나요?

[fix] actuator 설정 변경

---

src/main/java/com/example/grapefield/events/EventsService.java
src/main/java/com/example/grapefield/events/post/PostController.java
src/main/java/com/example/grapefield/events/post/PostService.java

[feat] 게시글 클릭시 조회수 증가로직 추가

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/java/com/example/grapefield/chat/repository/custom/ChatRoomRepositoryCustom.java
src/main/java/com/example/grapefield/chat/repository/custom/ChatRoomRepositoryImpl.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java

#139 
채팅 리스트 카테고리 수정
어떤 변경 사항이 있나요?

[#139] 채팅 리스트 카테고리 수정

---

Jenkinsfile

[#149] 젠킨스 파일 수정

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
src/main/resources/application.yml

#151 #152 
카테고리 뮤지컬 추가, application.yaml에 time-zone 추가
어떤 변경 사항이 있나요?

Fix/chat/category 카테고리 뮤지컬 추가, application.yaml에 time-zone 추가

---

k8s/backend-deployment.yml

#158
병합과정에서 누락된 코드 재병합 
어떤 변경 사항이 있나요?

Fix/chat/kafka 누락된 코드 재병합

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomDetailController.java
src/main/java/com/example/grapefield/chat/model/response/ChatMessagePageResp.java
src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/java/com/example/grapefield/chat/service/ChatRoomService.java

#169
채팅방 무한스크롤 전용으로 페이지네이션 활용하여 DTO 와 컨트롤러 작성
어떤 변경 사항이 있나요?

[feat] 채팅방 무한스크롤

---

src/main/java/com/example/grapefield/chat/controller/ChatRoomDetailController.java

null
병합과정에서 도커 이미지 라벨이 변경된 것이 누락되어, 젠킨스 자동배포를 위한 테스트 커밋입니다.

[chore] 쿠버네티스 젠킨스 배포 시도를 위한 테스트용 커밋 (REST API 문서 수정)

---

src/main/resources/application.yml

Update application.yml 병합과정에서 누락된 코드 되돌리기

---

src/main/java/com/example/grapefield/config/RedisConfig.java
src/main/java/com/example/grapefield/config/websocket/WebSocketConfig.java
src/main/resources/application.yml

#179 
협업을 위하여 RedisConfig에 jsonRedisTemplate 추가한 것을 병합합니다.
어떤 변경 사항이 있나요?
레디스 고도화기능 협업을 위하여 RedisConfig에 jsonRedisTemplate 추가한 것을 병합합니다. 기능을 완성한 것이 아닙니다.

[feat] RedisConfig에 jsonRedisTemplate 추가

---

src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
src/main/java/com/example/grapefield/chat/kafka/ChatParticipantEventKafkaConsumer.java
src/main/java/com/example/grapefield/chat/model/response/ChatParticipantEventResp.java
src/main/java/com/example/grapefield/chat/model/response/UserChatListEventResp.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/java/com/example/grapefield/chat/service/ChatParticipantService.java
src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java
src/main/java/com/example/grapefield/chat/service/ChatRoomMemberService.java
src/main/java/com/example/grapefield/chat/service/UserChatListService.java

#183 #184 
채팅방 인원수, 채팅방 목록 개선
어떤 변경 사항이 있나요?

Feat/chat/redis participant 채팅방 인원수, 채팅방 목록 개선

---

src/main/java/com/example/grapefield/chat/kafka/ChatParticipantEventKafkaConsumer.java
src/main/resources/application.yml

#191 
카프카 로직 수정
어떤 변경 사항이 있나요?

[#191] 카프카 로직 수정

---

src/main/java/com/example/grapefield/elasticsearch/ElasticsearchAdminController.java
src/main/java/com/example/grapefield/elasticsearch/EventDocument.java
src/main/java/com/example/grapefield/elasticsearch/EventDocumentMapper.java
src/main/java/com/example/grapefield/elasticsearch/EventSearchService.java
src/main/java/com/example/grapefield/events/EventsSearchController.java
src/main/java/com/example/grapefield/events/EventsSearchService.java

#176
원하는 결과만 나올 수 있게 es 수정함 -> 성고옹~!
어떤 변경 사항이 있나요?

#176 원하는 결과만 나올 수 있게 es 수정함

---

src/main/resources/application.yml

[fix] ES 관련 설정 환경변수 변경

---

README.md
devops/README.md
src/main/java/com/example/grapefield/events/post/model/entity/Post.java
src/main/java/com/example/grapefield/events/post/model/entity/PostComment.java
src/main/java/com/example/grapefield/events/review/model/entity/Review.java

develop을 main에 머지
어떤 변경 사항이 있나요?

main <- develop pull request

---

src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java

#182
redis set에서 이미 존재하는 지 확인하는 조건 분기식에 잘못된 조건 제거함
어떤 변경 사항이 있나요?

[feat/chat/heart] 분기문 조건식 오류 수정

---

src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
src/main/java/com/example/grapefield/chat/service/TextCortexSummarizer.java

k8s에 환경변수 반영하여 병합

---

Dockerfile.elasticsearch

[fix] Seunjeon 플러그인 삭제

---

build.gradle
src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java
src/main/java/com/example/grapefield/elasticsearch/EventDocument.java
src/main/resources/application.yml

버전 업그레이드를 통해 스웨거 문제 수정
어떤 변경 사항이 있나요?

[fix] 스웨거 문제 수정

---

src/main/resources/application.yml

[fix] swagger 샘플 페이지 뜨지 않도록 설정

---

src/main/java/com/example/grapefield/config/SwaggerConfig.java

[fix] swagger yml 오류 수정

---

src/main/java/com/example/grapefield/chat/controller/RedisStatusController.java
src/main/java/com/example/grapefield/config/SecurityConfig.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java

[fix] swagger cors 설정 추가

---

src/main/java/com/example/grapefield/config/SwaggerConfig.java

[fix] swagger openapi 버전 수정

---

README.md
src/main/java/com/example/grapefield/config/SwaggerConfig.java
src/main/java/com/example/grapefield/config/filter/JwtFilter.java
src/main/resources/application.yml

[fix] swagger 지정된 controller만 생성

---

src/main/java/com/example/grapefield/chat/service/HighlightCreationService.java
src/main/java/com/example/grapefield/chat/service/HighlightDetectionService.java
src/main/java/com/example/grapefield/chat/service/TextCortexSummarizer.java
src/main/resources/application.yml

#241
- API KEY값 환경변수 바인딩 시 application.yml에서 큰 따옴표로 한 번 더 묶어줌으로써 바인딩 오류 해결
- 크레딧 소진 혹은 토큰 값이 너무 긴 경우에 응답이 제대로 되지 않는 경우를 대비하여 분기처리하고 수동로직으로 결과값 반환하도록 함
어떤 변경 사항이 있나요?

feat/chat/highlight_summary 인공지능 요약 응답 코드 개선
